#!/bin/sh 

if grep -qE '\s?psplash=false\s?' /proc/cmdline; then
	echo "Boot splashscreen disabled"
	exit 0;
fi

. /etc/init.d/functions
. /etc/default/dotplash

export TMPDIR=/mnt/.splash
mount tmpfs -t tmpfs $TMPDIR -o,size=40k

/usr/bin/dotsplash $PARAMS &

# Timetrap against hanging with splash hiding console messages.
(sleep 120; dotsplash-write "QUIT") &
